export const products = [
  {
      "rowNumber": 671,
      "idProduct": 16896,
      "name": "UNSEEN LSR NAVY BLUE",
      "referenceCode": "RSC18BM0105001",
      "priceBeforeDiscount": 145000,
      "price": 145000,
      "quantity": 0,
      "sequenceNumber": 7980,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSUNSEEN-LSR-NAVY-BLUE",
      "cover": "http://manage.schofficial.com/assets/images/product/unseen-lsr-navy-blue-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 670,
      "idProduct": 16893,
      "name": "ART SYNTH LSS NAVY BLUE",
      "referenceCode": "RSC18BM0103001",
      "priceBeforeDiscount": 140000,
      "price": 140000,
      "quantity": 2,
      "sequenceNumber": 7977,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSART-SYNTH-LSS-NAVY-BLUE",
      "cover": "http://manage.schofficial.com/assets/images/product/art-synth-lss-navy-blue-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 669,
      "idProduct": 16892,
      "name": "AREOLES SS NAVY BLUE",
      "referenceCode": "RSC18BM0101017",
      "priceBeforeDiscount": 120000,
      "price": 120000,
      "quantity": 4,
      "sequenceNumber": 7976,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSAREOLES-SS-NAVY-BLUE",
      "cover": "http://manage.schofficial.com/assets/images/product/areoles-ss-navy-blue-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 668,
      "idProduct": 16890,
      "name": "MOCK SS DARK GREEN",
      "referenceCode": "RSC18BM0101015",
      "priceBeforeDiscount": 120000,
      "price": 100000,
      "quantity": 3,
      "sequenceNumber": 7974,
      "totalDiscount": 20000,
      "typeDiscountPercent": false,
      "discount": 20000,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSMOCK-SS-DARK-GREEN",
      "cover": "http://manage.schofficial.com/assets/images/product/mock-ss-dark-green-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 667,
      "idProduct": 16888,
      "name": "FLAMINGO SS DARK GREEN",
      "referenceCode": "RSC18BM0101013",
      "priceBeforeDiscount": 120000,
      "price": 120000,
      "quantity": 4,
      "sequenceNumber": 7972,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSFLAMINGO-SS-DARK-GREEN",
      "cover": "http://manage.schofficial.com/assets/images/product/flamingo-ss-dark-green-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 666,
      "idProduct": 16887,
      "name": "MOCK SS DARK MAROON",
      "referenceCode": "RSC18BM0101012",
      "priceBeforeDiscount": 120000,
      "price": 108000,
      "quantity": 68,
      "sequenceNumber": 7971,
      "totalDiscount": 12000,
      "typeDiscountPercent": true,
      "discount": 10,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSMOCK-SS-DARK-MAROON",
      "cover": "http://manage.schofficial.com/assets/images/product/mock-ss-dark-maroon-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 665,
      "idProduct": 16886,
      "name": "REGULARITY SS DARK GREEN",
      "referenceCode": "RSC18BM0101006",
      "priceBeforeDiscount": 120000,
      "price": 120000,
      "quantity": 3,
      "sequenceNumber": 7970,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSREGULARITY-SS-DARK-GREEN",
      "cover": "http://manage.schofficial.com/assets/images/product/regularity-ss-dark-green-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 664,
      "idProduct": 16885,
      "name": "UNSEEN SS BLACK",
      "referenceCode": "RSC18AM0101024",
      "priceBeforeDiscount": 120000,
      "price": 120000,
      "quantity": 2,
      "sequenceNumber": 7969,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSUNSEEN-SS-BLACK",
      "cover": "http://manage.schofficial.com/assets/images/product/unseen-ss-black-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 663,
      "idProduct": 16884,
      "name": "POLO ART SYNTH SS BLACK",
      "referenceCode": "RSC18BM0601008",
      "priceBeforeDiscount": 165000,
      "price": 165000,
      "quantity": 3,
      "sequenceNumber": 7968,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-SHIRTSPOLO-ART-SYNTH-SS-BLACK",
      "cover": "http://manage.schofficial.com/assets/images/product/polo-art-synth-ss-black-2.jpg",
      "defaultCategory": "SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 662,
      "idProduct": 16882,
      "name": "SDT 79 DARK GREEN-DARK BROWN-OFF WHITE WHITE WHITE WHITE WHITE",
      "referenceCode": "RSC18BM0208009",
      "priceBeforeDiscount": 245000,
      "price": 200000,
      "quantity": 0,
      "sequenceNumber": 7966,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-JACKETSSDT-79-DARK-GREEN-DARK-BROWN-OFF-WHITE",
      "cover": "http://manage.schofficial.com/assets/images/product/sdt-79-dark-green-dark-brown-off-white-2.jpg",
      "defaultCategory": "JACKET",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  }
]