export const products = [
  {
      "rowNumber": 377,
      "idProduct": 16893,
      "name": "ART SYNTH LSS NAVY BLUE",
      "referenceCode": "RSC18BM0103001",
      "priceBeforeDiscount": 140000,
      "price": 140000,
      "quantity": 0,
      "sequenceNumber": 7977,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSART-SYNTH-LSS-NAVY-BLUE",
      "cover": "http://manage.schofficial.com/assets/images/product/art-synth-lss-navy-blue-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 376,
      "idProduct": 16892,
      "name": "AREOLES SS NAVY BLUE",
      "referenceCode": "RSC18BM0101017",
      "priceBeforeDiscount": 120000,
      "price": 120000,
      "quantity": 4,
      "sequenceNumber": 7976,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSAREOLES-SS-NAVY-BLUE",
      "cover": "http://manage.schofficial.com/assets/images/product/areoles-ss-navy-blue-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 375,
      "idProduct": 16890,
      "name": "MOCK SS DARK GREEN",
      "referenceCode": "RSC18BM0101015",
      "priceBeforeDiscount": 120000,
      "price": 100000,
      "quantity": 3,
      "sequenceNumber": 7974,
      "totalDiscount": 20000,
      "typeDiscountPercent": false,
      "discount": 20000,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSMOCK-SS-DARK-GREEN",
      "cover": "http://manage.schofficial.com/assets/images/product/mock-ss-dark-green-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 374,
      "idProduct": 16888,
      "name": "FLAMINGO SS DARK GREEN",
      "referenceCode": "RSC18BM0101013",
      "priceBeforeDiscount": 120000,
      "price": 120000,
      "quantity": 4,
      "sequenceNumber": 7972,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSFLAMINGO-SS-DARK-GREEN",
      "cover": "http://manage.schofficial.com/assets/images/product/flamingo-ss-dark-green-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 373,
      "idProduct": 16887,
      "name": "MOCK SS DARK MAROON",
      "referenceCode": "RSC18BM0101012",
      "priceBeforeDiscount": 120000,
      "price": 108000,
      "quantity": 68,
      "sequenceNumber": 7971,
      "totalDiscount": 12000,
      "typeDiscountPercent": true,
      "discount": 10,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSMOCK-SS-DARK-MAROON",
      "cover": "http://manage.schofficial.com/assets/images/product/mock-ss-dark-maroon-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 372,
      "idProduct": 16886,
      "name": "REGULARITY SS DARK GREEN",
      "referenceCode": "RSC18BM0101006",
      "priceBeforeDiscount": 120000,
      "price": 120000,
      "quantity": 3,
      "sequenceNumber": 7970,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSREGULARITY-SS-DARK-GREEN",
      "cover": "http://manage.schofficial.com/assets/images/product/regularity-ss-dark-green-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 371,
      "idProduct": 16885,
      "name": "UNSEEN SS BLACK",
      "referenceCode": "RSC18AM0101024",
      "priceBeforeDiscount": 120000,
      "price": 120000,
      "quantity": 2,
      "sequenceNumber": 7969,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSUNSEEN-SS-BLACK",
      "cover": "http://manage.schofficial.com/assets/images/product/unseen-ss-black-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 370,
      "idProduct": 16862,
      "name": "PORTABLE TSR WHITE-CHOCOLATE BROWN",
      "referenceCode": "RSC18BM0108004",
      "priceBeforeDiscount": 135000,
      "price": 135000,
      "quantity": 4,
      "sequenceNumber": 7946,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 1,
      "metaKeyword": "RSCH-MALE-T-SHIRTSPORTABLE-TSR-WHITE-CHOCOLATE-BROWN",
      "cover": "http://manage.schofficial.com/assets/images/product/portable-tsr-white-chocolate-brown-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 369,
      "idProduct": 16861,
      "name": "PORTABLE TSR WHITE-NAVY BLUE",
      "referenceCode": "RSC18BM0108003",
      "priceBeforeDiscount": 135000,
      "price": 135000,
      "quantity": 4,
      "sequenceNumber": 7945,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 0.8,
      "metaKeyword": "RSCH-MALE-T-SHIRTSPORTABLE-TSR-WHITE-NAVY-BLUE",
      "cover": "http://manage.schofficial.com/assets/images/product/portable-tsr-white-navy-blue-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  },
  {
      "rowNumber": 368,
      "idProduct": 16860,
      "name": "C&N LSS MISTY M80",
      "referenceCode": "RSC18BM0103003",
      "priceBeforeDiscount": 155000,
      "price": 155000,
      "quantity": 2,
      "sequenceNumber": 7944,
      "totalDiscount": 0,
      "typeDiscountPercent": false,
      "discount": 0,
      "weight": 0.9,
      "metaKeyword": "RSCH-MALE-T-SHIRTSC&N-LSS-MISTY-M80",
      "cover": "http://manage.schofficial.com/assets/images/product/c&n-lss-misty-m80-2.jpg",
      "defaultCategory": "T-SHIRT",
      "idManufacturer": 1,
      "manufacturer": "RSCH"
  }
]